### ISSUE TITLE
PIの精度

### ISSUE THREAD

**Issue by ei1333** [Luzhiled/comp-geometry#20]
https://github.com/Luzhiled/comp-geometry/blob/a82700b1e86c1961fdae74b243385737e4b51382/src/base.hpp#L10

これだと acos(double) が呼び出されて精度が悪いかも

```cpp
const real_number PI = acos(static_cast< real_number >(-1));
```

とするか

```cpp
const real_number PI = acosl(-1);
```

としたほうがいいようなきがする

**Comment by Luzhiled** [comment]
ありがとう　直します
