### ISSUE TITLE
cross_point_llがバグってませんでしょうか

### ISSUE THREAD

**Issue by matumoto1234** [Luzhiled/comp-geometry#43]
突然のissue失礼します

https://github.com/Luzhiled/comp-geometry/blob/08c3995659386521dac6c36809cd337c2c50baf6/src/cross_point_ll.hpp#L11

よく理解したわけではないのでエスパーですが、 `l1.b - l2.a` が `l2.b - l2.a` の間違いかもしれません

**Comment by Luzhiled** [comment]
確かめたけど問題なさそう、報告ありがとう

必要であれば会ったときにでも解説します
